src/Entity/Vehicule.php
<?php

namespace App\Entity;

use App\Repository\VehiculeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


#[ORM\Entity(repositoryClass: VehiculeRepository::class)]
#[UniqueEntity('image')]

class Vehicule
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 1, max: 100)]
    private ?string $nom;

    #[ORM\Column(length: 100)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 1, max: 100)]
    private ?string $modele;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 1, max: 65000)]
    private ?string $description;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    #[Assert\NotBlank()]
    #[Assert\NotNull()]
    private \DateTimeInterface $date_creation;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 1, max: 255)]
    protected ?string $image;

    #[ORM\Column]
    #[Assert\NotNull()]
    #[Assert\NotBlank()]
    private ?bool $en_vente = true;


    public function __construct()
    {
        $this->date_creation = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function isEnVente(): ?bool
    {
        return $this->en_vente;
    }

    public function setEnVente(bool $en_vente): static
    {
        $this->en_vente = $en_vente;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\VehiculeRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;


class HomeController extends AbstractController
{
    /**
     * Ce contrôleur affiche tous les véhicules
     *
     * @param VehiculeRepository $repository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */

     #[Route('/', name: 'app_home', methods: ['GET'])]
    public function index(VehiculeRepository $repository, PaginatorInterface $paginator, Request $request): Response
    {
        $vehicules = $paginator->paginate(
            $repository->findAll(),
            $request->query->getInt('page', 1),
            9
        );
        return $this->render('home/index.html.twig', [
            'vehicules' => $vehicules,
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}MalikAuto - Accueil
{% endblock %}

{% block body %}
	<div class="container mt-4">
		{% for message in app.flashes('success') %}
			<div class="alert alert-success mt-4">
				{{ message }}
			</div>
		{% endfor %}
		<h1 class="display-4 p-2 text-center">Bienvenue sur MalikAuto</h1>
		<h3 class="lead text-center">Votre Destination Automobile en Ligne</h3>
		{% if not vehicules.items is same as([]) %}
			<div class="jumbotron text-center">
				<div class="d-flex justify-content-between">
					<div class="count text-start d-flex align-items-center">
						Il y a
						{{ vehicules.getTotalItemCount }}
						véhicules au total.
					</div>
					<div class="navigation pagination-sm mt-3 ml-auto">
						{{ knp_pagination_render(vehicules) }}
					</div>
				</div>
				<tbody>
					<div class="row row-cols-1 row-cols-md-3 g-4">
						{% for vehicule in vehicules %}
							<div class="col">
								<div class="card h-100">
									<div class="card-header">
										{% if vehicule.enVente %}
											<h5 class="text-success">En vente</h5>
										{% else %}
											<h5 class="text-danger">Vendu</h5>
										{% endif %}
									</div>
									<img src="{{ vehicule.image }}" class="card-img-top" alt="Image du véhicule">
									<div class="card-body">
										<h5 class="card-title">{{ vehicule.nom }}
										</h5>
										<h5 class="card-title">{{ vehicule.modele }}
										</h5>
										<p class="card-text">{{ vehicule.description|slice(0, 50) }}</p>
										{% if vehicule.description|length > 100 %}
											<button class="btn btn-link" data-bs-toggle="modal" data-bs-target="#modal{{ vehicule.id }}">Voir plus</button>
										{% endif %}
									</div>
									<div class="card-footer">
										<h5 class="card-title">Publié le :
											{{ vehicule.dateCreation|date('d/m/Y') }}
										</h5>
									</div>
									<div class="modal fade" id="modal{{ vehicule.id }}" tabindex="-1" role="dialog" aria-labelledby="modalLabel{{ vehicule.id }}" aria-hidden="true">
										<div class="modal-dialog" role="document">
											<div class="modal-content">
												<div class="modal-header">
													<h5 class="modal-title" id="modalLabel{{ vehicule.id }}">Description complète</h5>
													<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
												</div>
												<div class="modal-body">
													{{ vehicule.description }}
												</div>
												<div class="modal-footer">
													<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
				</tbody>
				<div class="d-flex justify-content-between">
					<div class="count text-start d-flex align-items-center">
						Il y a
						{{ vehicules.getTotalItemCount }}
						véhicules au total.
					</div>
					<div class="navigation pagination-sm mt-3 ml-auto">
						{{ knp_pagination_render(vehicules) }}
					</div>
				</div>
			{% else %}
				<h4 class="text-danger text-center">Il n'y a pas de véhicule ...</h4>
			{% endif %}
		</div>
	{% endblock %}